-- Correcoes incrementais e preservadoras para bases que ja executaram versoes
-- parciais das migrations de clientes/afiliados. Nenhuma coluna e recriada.
create extension if not exists pgcrypto;

alter table public.cliente_empreendimentos
  add column if not exists visivel boolean not null default true,
  add column if not exists exibir_imagens boolean not null default false,
  add column if not exists exibir_descricao boolean not null default false,
  add column if not exists exibir_preco boolean not null default false,
  add column if not exists exibir_especificacoes boolean not null default false,
  add column if not exists exibir_investimento boolean not null default false,
  add column if not exists exibir_fluxo boolean not null default false,
  add column if not exists mensagem_personalizada text;

alter table public.afiliado_produtos
  add column if not exists exibir_imagens boolean not null default false,
  add column if not exists exibir_descricao boolean not null default false,
  add column if not exists exibir_preco boolean not null default false,
  add column if not exists exibir_entrada_parcelas boolean not null default false,
  add column if not exists exibir_comissao boolean not null default false,
  add column if not exists exibir_especificacoes boolean not null default false;

-- Links guardam somente referencias e permissoes. Conteudo protegido e entregue
-- pela RPC abaixo apos validacao; o token armazenado e apenas um hash.
create table if not exists public.links_temporarios (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  titulo text not null,
  publico text not null check (publico in ('cliente','afiliado','investidor')),
  cliente_id_text text,
  afiliado_id uuid references public.afiliados(id) on delete set null,
  empreendimento_ids_text text[] not null default '{}',
  permissoes jsonb not null default '{}'::jsonb,
  senha_hash text,
  expira_em timestamptz not null,
  max_acessos integer check (max_acessos is null or max_acessos > 0),
  acessos integer not null default 0,
  ultimo_acesso_em timestamptz,
  revogado_em timestamptz,
  criado_por uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.links_temporarios
  add column if not exists token_hash text,
  add column if not exists titulo text,
  add column if not exists publico text,
  add column if not exists cliente_id_text text,
  add column if not exists afiliado_id uuid,
  add column if not exists empreendimento_ids_text text[] not null default '{}',
  add column if not exists permissoes jsonb not null default '{}'::jsonb,
  add column if not exists senha_hash text,
  add column if not exists expira_em timestamptz,
  add column if not exists max_acessos integer,
  add column if not exists acessos integer not null default 0,
  add column if not exists ultimo_acesso_em timestamptz,
  add column if not exists revogado_em timestamptz,
  add column if not exists criado_por uuid,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
create unique index if not exists links_temporarios_token_hash_key on public.links_temporarios(token_hash) where token_hash is not null;

create table if not exists public.links_temporarios_acessos (
  id bigint generated by default as identity primary key,
  link_id uuid not null references public.links_temporarios(id) on delete cascade,
  acessado_em timestamptz not null default now(),
  user_agent text,
  ip_hash text,
  sucesso boolean not null,
  motivo text
);

create index if not exists links_temporarios_validade_idx
  on public.links_temporarios(expira_em) where revogado_em is null;

alter table public.links_temporarios enable row level security;
alter table public.links_temporarios_acessos enable row level security;
alter table public.apresentacoes enable row level security;
drop policy if exists "Usuários autenticados gerenciam apresentações" on public.apresentacoes;
drop policy if exists "Leitura publica de apresentacoes ativas" on public.apresentacoes;
drop policy if exists "Permitir leitura publica de apresentacoes" on public.apresentacoes;
drop policy if exists "apresentacoes somente admin" on public.apresentacoes;
create policy "apresentacoes somente admin" on public.apresentacoes for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
drop policy if exists "links somente admin" on public.links_temporarios;
create policy "links somente admin" on public.links_temporarios for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
drop policy if exists "acessos de links somente admin" on public.links_temporarios_acessos;
create policy "acessos de links somente admin" on public.links_temporarios_acessos for select to authenticated
  using (public.is_admin());

-- Criacao atomica: devolve o segredo uma unica vez e persiste somente o hash.
create or replace function public.criar_link_temporario(
  p_titulo text, p_publico text, p_expira_em timestamptz,
  p_empreendimento_ids text[] default '{}', p_permissoes jsonb default '{}'::jsonb,
  p_cliente_id text default null, p_afiliado_id uuid default null,
  p_senha text default null, p_max_acessos integer default null
) returns table(id uuid, token text)
language plpgsql security definer set search_path = public, extensions as $$
declare segredo text := encode(gen_random_bytes(32), 'hex'); novo_id uuid;
begin
  if not public.is_admin() then raise exception 'Apenas administrador pode criar links'; end if;
  if p_expira_em <= now() then raise exception 'A expiracao deve estar no futuro'; end if;
  if p_publico not in ('cliente','afiliado','investidor') then raise exception 'Publico invalido'; end if;
  insert into public.links_temporarios as lt(codigo,bloqueado_manualmente,token_hash,titulo,publico,cliente_id_text,afiliado_id,
    empreendimento_ids_text,permissoes,senha_hash,expira_em,max_acessos)
  values (encode(gen_random_bytes(16),'hex'),false,encode(digest(segredo,'sha256'),'hex'),trim(p_titulo),p_publico,p_cliente_id,p_afiliado_id,
    coalesce(p_empreendimento_ids,'{}'),coalesce(p_permissoes,'{}'::jsonb),
    case when nullif(p_senha,'') is null then null else crypt(p_senha,gen_salt('bf')) end,
    p_expira_em,p_max_acessos) returning lt.id into novo_id;
  return query select novo_id, segredo;
end $$;

create or replace function public.revogar_link_temporario(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Apenas administrador pode revogar links'; end if;
  update public.links_temporarios set revogado_em=now(),bloqueado_manualmente=true,updated_at=now() where id=p_id;
end $$;

grant execute on function public.criar_link_temporario(text,text,timestamptz,text[],jsonb,text,uuid,text,integer) to authenticated;
grant execute on function public.revogar_link_temporario(uuid) to authenticated;

create or replace function public.resolver_link_temporario(p_token text, p_senha text default null, p_user_agent text default null, p_ip text default null)
returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare l public.links_temporarios%rowtype; resultado jsonb; sucesso boolean := false; motivo text;
begin
  select * into l from public.links_temporarios where token_hash=encode(digest(coalesce(p_token,''),'sha256'),'hex') for update;
  if l.id is null then return jsonb_build_object('ok',false,'codigo','invalido'); end if;
  if l.revogado_em is not null or coalesce(l.bloqueado_manualmente,false) then motivo:='revogado';
  elsif l.expira_em<=now() then motivo:='expirado';
  elsif l.max_acessos is not null and l.acessos>=l.max_acessos then motivo:='limite';
  elsif l.senha_hash is not null and crypt(coalesce(p_senha,''),l.senha_hash)<>l.senha_hash then motivo:='senha';
  else sucesso:=true; end if;
  insert into public.links_temporarios_acessos(link_id,user_agent,ip_hash,sucesso,motivo) values(l.id,left(p_user_agent,500),case when p_ip is null then null else encode(digest(p_ip,'sha256'),'hex') end,sucesso,motivo);
  if not sucesso then return jsonb_build_object('ok',false,'codigo',motivo,'senha_necessaria',l.senha_hash is not null); end if;
  update public.links_temporarios set acessos=acessos+1,ultimo_acesso_em=now(),updated_at=now() where id=l.id;
  select jsonb_build_object('ok',true,'titulo',l.titulo,'publico',l.publico,'expira_em',l.expira_em,'permissoes',l.permissoes,
    'empreendimentos',coalesce(jsonb_agg(jsonb_build_object(
      'id',e.id::text,'nome',e.nome,'cidade',e.cidade,'bairro',e.bairro,'status',e.status,
      'descricao',case when coalesce((l.permissoes->>'descricao')::boolean,false) then e.descricao end,
      'preco',case when coalesce((l.permissoes->>'preco')::boolean,false) then e.faixa_preco end,
      'caracteristicas',case when coalesce((l.permissoes->>'descricao')::boolean,false) then e.caracteristicas end,
      'midias',case when coalesce((l.permissoes->>'imagens')::boolean,false) then (select coalesce(jsonb_agg(ei.storage_path) filter(where ei.storage_path is not null),'[]'::jsonb) from public.empreendimento_imagens ei where ei.empreendimento_id=e.id) else '[]'::jsonb end,
      'pdf_path',case when coalesce((l.permissoes->>'pdf')::boolean,false) then (select a.storage_path from public.apresentacoes a where a.empreendimento_id=e.id and a.ativo limit 1) end
    )) filter(where e.id is not null),'[]'::jsonb)) into resultado
  from public.empreendimentos e where e.id::text=any(l.empreendimento_ids_text);
  return resultado;
end $$;
grant execute on function public.resolver_link_temporario(text,text,text,text) to anon,authenticated;

-- Storage confidencial deve usar URLs assinadas. A migration converte os
-- buckets conhecidos para privados sem apagar objetos existentes.
update storage.buckets set public=false where id in ('empreendimentos','pdfs');

drop policy if exists "Acesso público às imagens de empreendimentos" on storage.objects;
drop policy if exists "Liberar leitura publica 21n7l_0" on storage.objects;
drop policy if exists "Permitir upload publico ht74h7_0" on storage.objects;
drop policy if exists "Delete autenticado para empreendimentos" on storage.objects;
drop policy if exists "Update autenticado para empreendimentos" on storage.objects;
drop policy if exists "Apresentacoes PDF atualizacao autenticada" on storage.objects;
drop policy if exists "Apresentacoes PDF envio autenticado" on storage.objects;
drop policy if exists "Apresentacoes PDF exclusao autenticada" on storage.objects;
drop policy if exists "Apresentacoes PDF leitura" on storage.objects;

drop policy if exists "midias privadas admin select" on storage.objects;
create policy "midias privadas admin select" on storage.objects for select to authenticated
  using (bucket_id in ('empreendimentos','pdfs') and public.is_admin());
drop policy if exists "midias privadas admin insert" on storage.objects;
create policy "midias privadas admin insert" on storage.objects for insert to authenticated
  with check (bucket_id in ('empreendimentos','pdfs') and public.is_admin());
drop policy if exists "midias privadas admin update" on storage.objects;
create policy "midias privadas admin update" on storage.objects for update to authenticated
  using (bucket_id in ('empreendimentos','pdfs') and public.is_admin())
  with check (bucket_id in ('empreendimentos','pdfs') and public.is_admin());
drop policy if exists "midias privadas admin delete" on storage.objects;
create policy "midias privadas admin delete" on storage.objects for delete to authenticated
  using (bucket_id in ('empreendimentos','pdfs') and public.is_admin());
