-- Infraestrutura exigida pelos módulos já existentes, com compatibilidade para IDs antigos.
alter table public.perfis_usuario drop constraint if exists perfis_usuario_perfil_check;
alter table public.perfis_usuario add constraint perfis_usuario_perfil_check
  check (perfil in ('admin', 'equipe', 'cliente', 'afiliado'));

create table if not exists public.indicadores_ticker_config (
  sku text primary key, ativo boolean not null default true, updated_at timestamptz not null default now()
);

do $$
declare indicador_id_type text;
declare empreendimento_id_type text;
declare unidade_id_type text;
begin
  select pg_catalog.format_type(a.atttypid, a.atttypmod) into indicador_id_type from pg_catalog.pg_attribute a where a.attrelid = 'public.indicadores'::regclass and a.attname = 'id' and not a.attisdropped;
  execute format('create table if not exists public.indicadores_historico (
    id bigint generated by default as identity primary key, indicador_id %s not null references public.indicadores(id) on delete cascade,
    data_referencia text not null, valor numeric not null, created_at timestamptz not null default now(), unique(indicador_id, data_referencia))', indicador_id_type);

  select pg_catalog.format_type(a.atttypid, a.atttypmod) into empreendimento_id_type from pg_catalog.pg_attribute a where a.attrelid = 'public.empreendimentos'::regclass and a.attname = 'id' and not a.attisdropped;
  select pg_catalog.format_type(a.atttypid, a.atttypmod) into unidade_id_type from pg_catalog.pg_attribute a where a.attrelid = 'public.unidades'::regclass and a.attname = 'id' and not a.attisdropped;
  execute format('create table if not exists public.historico_tabelas_preco (
    id bigint generated by default as identity primary key,
    empreendimento_id %s not null references public.empreendimentos(id) on delete cascade,
    unidade_id %s references public.unidades(id) on delete set null,
    codigo_unidade text, mes_referencia integer not null check(mes_referencia between 1 and 12),
    ano_referencia integer not null check(ano_referencia between 2000 and 2100),
    valor_tabela numeric not null, entrada_sugerida numeric, fluxo_dados jsonb not null default ''{}''::jsonb,
    created_at timestamptz not null default now())', empreendimento_id_type, unidade_id_type);
end $$;

create or replace function public.get_server_time()
returns timestamptz language sql stable security invoker as $$ select now() $$;
grant execute on function public.get_server_time() to authenticated;

create or replace function public.vincular_afiliado_email(p_afiliado_id uuid, p_email text)
returns boolean language plpgsql security definer set search_path = public, auth as $$
declare conta uuid;
begin
  if not public.is_admin() then raise exception 'Apenas administrador pode vincular afiliados'; end if;
  select id into conta from auth.users where lower(email) = lower(trim(p_email)) limit 1;
  if conta is null then return false; end if;
  update public.afiliados set user_id = conta, updated_at = now() where id = p_afiliado_id;
  insert into public.perfis_usuario(user_id, perfil, ativo) values (conta, 'afiliado', true)
  on conflict (user_id) do update set perfil = 'afiliado', ativo = true, updated_at = now();
  return true;
end;
$$;
grant execute on function public.vincular_afiliado_email(uuid, text) to authenticated;
