import { useEffect, useState } from "react";
import { Plus, RefreshCw, Save, Trash2 } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { refreshExchangeRate } from "@/lib/exchangeRate";
type Page={id?:number;titulo:string;caminho:string;ativa:boolean;exige_login:boolean;protecao_obrigatoria:boolean;ordem:number};
type Config={cambio_automatico:boolean;tipo_ptax:"compra"|"venda";margem_cambio_percentual:number;cotacao_manual:number|null};
const blank:Page={titulo:"",caminho:"/",ativa:true,exige_login:false,protecao_obrigatoria:false,ordem:0};
export default function AcessoSite(){
 const[pages,setPages]=useState<Page[]>([]),[draft,setDraft]=useState<Page>(blank),[message,setMessage]=useState("");
 const[config,setConfig]=useState<Config>({cambio_automatico:true,tipo_ptax:"venda",margem_cambio_percentual:0,cotacao_manual:null});
 const load=async()=>{const[p,c]=await Promise.all([supabase.from("site_paginas").select("*").order("ordem"),supabase.from("site_configuracoes").select("*").eq("id",1).single()]);if(p.error)setMessage("Execute a migration de acesso no Supabase.");else setPages((p.data||[])as Page[]);if(c.data)setConfig(c.data as Config)};
 // A consulta é assíncrona; as atualizações só ocorrem após a resposta externa.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[]);
 const savePage=async(page:Page)=>{const payload={...page,exige_login:page.protecao_obrigatoria||page.exige_login,updated_at:new Date().toISOString()};const r=page.id?await supabase.from("site_paginas").update(payload).eq("id",page.id):await supabase.from("site_paginas").insert(payload);setMessage(r.error?.message||"Página salva.");if(!r.error){setDraft(blank);void load()}};
 const remove=async(page:Page)=>{if(page.protecao_obrigatoria||!page.id||!confirm(`Excluir ${page.titulo}?`))return;await supabase.from("site_paginas").delete().eq("id",page.id);void load()};
 const saveConfig=async()=>{const{error}=await supabase.from("site_configuracoes").upsert({id:1,...config,updated_at:new Date().toISOString()});setMessage(error?.message||"Configurações salvas.")};const refresh=async()=>{try{const rate=await refreshExchangeRate();setMessage(rate?`PTAX atualizada: ${rate.value.toLocaleString("pt-BR",{minimumFractionDigits:4,maximumFractionDigits:4})} · ${rate.date||"data não informada"}.` : "Nenhuma cotação válida retornada.")}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível atualizar a PTAX.")}};
 const input={background:"#09090b",border:"1px solid #3f3f46",color:"#fff",borderRadius:6,padding:8}as const;
 return <div style={{color:"#eee",display:"grid",gap:18}}><header><h1>Configurações do site</h1><p style={{color:"#888"}}>Acesso, ordem das páginas, idiomas e câmbio.</p></header>{message&&<div>{message}</div>}<section style={{background:"#101012",padding:16,borderRadius:9}}><h2>Páginas</h2>{pages.map((page,index)=><div key={page.id} style={{display:"grid",gridTemplateColumns:"2fr 2fr 70px auto auto auto",gap:8,marginBottom:8}}><input style={input} value={page.titulo} onChange={e=>setPages(x=>x.map((p,i)=>i===index?{...p,titulo:e.target.value}:p))}/><input style={input} value={page.caminho} onChange={e=>setPages(x=>x.map((p,i)=>i===index?{...p,caminho:e.target.value}:p))}/><input style={input} type="number" value={page.ordem} onChange={e=>setPages(x=>x.map((p,i)=>i===index?{...p,ordem:Number(e.target.value)}:p))}/><label><input type="checkbox" checked={page.ativa} onChange={e=>setPages(x=>x.map((p,i)=>i===index?{...p,ativa:e.target.checked}:p))}/>Ativa</label><label><input type="checkbox" checked={page.exige_login} disabled={page.protecao_obrigatoria} onChange={e=>setPages(x=>x.map((p,i)=>i===index?{...p,exige_login:e.target.checked}:p))}/>Login</label><span><button onClick={()=>void savePage(page)}><Save size={15}/></button><button onClick={()=>void remove(page)} disabled={page.protecao_obrigatoria}><Trash2 size={15}/></button></span></div>)}<div style={{display:"flex",gap:8}}><input style={input} placeholder="Título" value={draft.titulo} onChange={e=>setDraft({...draft,titulo:e.target.value})}/><input style={input} placeholder="/caminho/" value={draft.caminho} onChange={e=>setDraft({...draft,caminho:e.target.value})}/><button onClick={()=>void savePage(draft)}><Plus size={15}/>Adicionar</button></div></section><section style={{background:"#101012",padding:16,borderRadius:9}}><h2>USD/BRL — PTAX</h2><div style={{display:"flex",gap:12,alignItems:"end",flexWrap:"wrap"}}><label><input type="checkbox" checked={config.cambio_automatico} onChange={e=>setConfig({...config,cambio_automatico:e.target.checked})}/>Automático</label><select style={input} value={config.tipo_ptax} onChange={e=>setConfig({...config,tipo_ptax:e.target.value as Config["tipo_ptax"]})}><option value="venda">Venda</option><option value="compra">Compra</option></select><input style={input} title="Margem percentual" type="number" step=".01" value={config.margem_cambio_percentual} onChange={e=>setConfig({...config,margem_cambio_percentual:Number(e.target.value)})}/><input style={input} title="Cotação manual" type="number" step=".000001" value={config.cotacao_manual??""} onChange={e=>setConfig({...config,cotacao_manual:e.target.value?Number(e.target.value):null})}/><button onClick={()=>void saveConfig()}><Save size={15}/>Salvar</button><button onClick={()=>void refresh()}><RefreshCw size={15}/>Atualizar PTAX</button></div></section></div>}
