import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, Save, Trash2, UserRound, X } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Cliente = { id: string; nome: string; telefone?: string | null; email?: string | null; cidade?: string | null; objetivo?: string | null; faixa_investimento?: number | null; entrada_disponivel?: number | null; capacidade_mensal?: number | null; status?: string | null; proximo_contato?: string | null; observacoes?: string | null };
type Form = { nome: string; telefone: string; email: string; cidade: string; objetivo: string; faixa_investimento: string; entrada_disponivel: string; capacidade_mensal: string; status: string; proximo_contato: string; observacoes: string };
const empty: Form = { nome: "", telefone: "", email: "", cidade: "", objetivo: "investimento", faixa_investimento: "", entrada_disponivel: "", capacidade_mensal: "", status: "novo", proximo_contato: "", observacoes: "" };
const money = (value?: number | null) => value ? new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(value) : "Não informado";

export default function Clientes() {
  const [items, setItems] = useState<Cliente[]>([]), [form, setForm] = useState<Form>(empty);
  const [query, setQuery] = useState(""), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  async function load() { const { data, error } = await supabase.from("clientes").select("*").order("created_at", { ascending: false }); if (error) setMessage("Aplique a migração de clientes no Supabase para ativar este módulo."); else { setItems((data || []) as Cliente[]); setMessage(""); } }
  // A consulta é assíncrona; as atualizações só ocorrem após a resposta externa.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => items.filter((item) => `${item.nome} ${item.telefone} ${item.email} ${item.cidade}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const update = (key: keyof Form, value: string) => setForm((old) => ({ ...old, [key]: value }));
  const edit = (item: Cliente) => { setEditingId(item.id); setForm({ nome:item.nome, telefone:item.telefone||"", email:item.email||"", cidade:item.cidade||"", objetivo:item.objetivo||"investimento", faixa_investimento:String(item.faixa_investimento||""), entrada_disponivel:String(item.entrada_disponivel||""), capacidade_mensal:String(item.capacidade_mensal||""), status:item.status||"novo", proximo_contato:item.proximo_contato||"", observacoes:item.observacoes||"" }); setOpen(true); };
  const remove = async (item: Cliente) => { if (!confirm(`Excluir o cliente ${item.nome}?`)) return; const { error } = await supabase.from("clientes").delete().eq("id", item.id); setMessage(error?.message || "Cliente excluído."); if (!error) void load(); };
  async function save() { if (!form.nome.trim()) return setMessage("Informe o nome do cliente."); setSaving(true); const payload = { nome: form.nome.trim(), telefone: form.telefone.trim() || null, email: form.email.trim() || null, cidade: form.cidade.trim() || null, objetivo: form.objetivo, faixa_investimento: Number(form.faixa_investimento) || null, entrada_disponivel: Number(form.entrada_disponivel) || null, capacidade_mensal: Number(form.capacidade_mensal) || null, status: form.status, proximo_contato: form.proximo_contato || null, observacoes: form.observacoes.trim() || null }; const result = editingId ? await supabase.from("clientes").update(payload).eq("id",editingId) : await supabase.from("clientes").insert(payload); setSaving(false); if (result.error) setMessage("Não foi possível salvar o cliente. Verifique a atualização do banco."); else { setEditingId(null); setForm(empty); setOpen(false); void load(); } }
  const panel = { background: "#101012", border: "1px solid #27272a", borderRadius: 10, padding: 16 } as const;
  const input = { width: "100%", boxSizing: "border-box", background: "#09090b", border: "1px solid #3f3f46", borderRadius: 7, padding: 10, color: "#fff" } as const;
  const button = { display: "inline-flex", alignItems: "center", gap: 6, background: "#c5a059", color: "#09090b", border: 0, borderRadius: 7, padding: "10px 13px", fontWeight: 800, cursor: "pointer" } as const;
  return <div style={{ color: "#f4f4f5", display: "grid", gap: 14 }}><header style={{ display: "flex", justifyContent: "space-between", alignItems: "end" }}><div><h1 style={{ margin: 0, fontSize: 24 }}>Clientes</h1><p style={{ color: "#8b8b95", margin: "5px 0 0", fontSize: 12 }}>Perfis, capacidade de investimento e histórico comercial.</p></div><button style={button} onClick={() => setOpen(true)}><Plus size={16}/>Novo cliente</button></header>
  {message && <div style={{ ...panel, borderColor: "#854d0e", color: "#fbbf24" }}>{message}</div>}
  <section style={panel}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><Search size={16} color="#71717a"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nome, telefone, e-mail ou cidade" style={input}/></div></section>
  <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))", gap: 10 }}>{visible.map((item) => <article key={item.id} style={panel}><div style={{ display: "flex", gap: 10, alignItems: "center" }}><UserRound size={19} color="#c5a059"/><div><strong>{item.nome}</strong><small style={{ display: "block", color: "#8b8b95", marginTop: 3 }}>{item.telefone || item.email || "Contato não informado"}</small></div><button onClick={()=>edit(item)} title="Editar"><Pencil size={14}/></button><button onClick={()=>void remove(item)} title="Excluir"><Trash2 size={14}/></button></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 14, fontSize: 12 }}><span style={{ color: "#8b8b95" }}>Imóvel desejado<strong style={{ display: "block", color: "#fff", marginTop: 3 }}>{money(item.faixa_investimento)}</strong></span><span style={{ color: "#8b8b95" }}>Entrada disponível<strong style={{ display: "block", color: "#fff", marginTop: 3 }}>{money(item.entrada_disponivel)}</strong></span><span style={{ color: "#8b8b95" }}>Mensal confortável<strong style={{ display: "block", color: "#fff", marginTop: 3 }}>{money(item.capacidade_mensal)}</strong></span><span style={{ color: "#8b8b95" }}>Etapa<strong style={{ display: "block", color: "#c5a059", marginTop: 3, textTransform: "capitalize" }}>{item.status || "novo"}</strong></span></div></article>)}</section>
  {open && <div style={{ position: "fixed", inset: 0, zIndex: 5000, background: "rgba(0,0,0,.78)", display: "grid", placeItems: "center", padding: 20 }}><section style={{ ...panel, width: "min(760px,100%)", maxHeight: "88vh", overflow: "auto" }}><header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}><h2 style={{ margin: 0, fontSize: 18 }}>{editingId ? "Editar cliente" : "Novo cliente"}</h2><button onClick={() => setOpen(false)} style={{ background: "none", border: 0, color: "#aaa", cursor: "pointer" }}><X/></button></header><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 11 }}>{([['nome','Nome *','text'],['telefone','Telefone / WhatsApp','text'],['email','E-mail','email'],['cidade','Cidade','text'],['faixa_investimento','Valor do imóvel desejado','number'],['entrada_disponivel','Entrada disponível','number'],['capacidade_mensal','Parcela mensal confortável','number'],['proximo_contato','Próximo contato','date']] as Array<[keyof Form,string,string]>).map(([key,label,type]) => <label key={key} style={{ color: "#a1a1aa", fontSize: 12 }}>{label}<input type={type} value={form[key]} onChange={(e) => update(key,e.target.value)} style={{ ...input, marginTop: 5 }}/></label>)}<label style={{ color: "#a1a1aa", fontSize: 12 }}>Objetivo<select value={form.objetivo} onChange={(e) => update('objetivo',e.target.value)} style={{ ...input, marginTop: 5 }}><option value="investimento">Investimento</option><option value="moradia">Moradia</option><option value="renda">Renda</option><option value="revenda">Revenda</option></select></label><label style={{ color: "#a1a1aa", fontSize: 12 }}>Etapa<select value={form.status} onChange={(e) => update('status',e.target.value)} style={{ ...input, marginTop: 5 }}><option value="novo">Novo</option><option value="qualificado">Qualificado</option><option value="simulacao">Simulação</option><option value="proposta">Proposta</option><option value="negociacao">Negociação</option></select></label><label style={{ color: "#a1a1aa", fontSize: 12, gridColumn: "1/-1" }}>Observações<textarea value={form.observacoes} onChange={(e) => update('observacoes',e.target.value)} rows={4} style={{ ...input, marginTop: 5 }}/></label></div><div style={{ display: "flex", justifyContent: "flex-end", marginTop: 15 }}><button style={button} onClick={() => void save()} disabled={saving}><Save size={16}/>{saving ? "Salvando..." : "Salvar cliente"}</button></div></section></div>}</div>;
}
