import { useEffect, useMemo, useState } from "react";
import { BarChart3, Check, MessageCircle, Pencil, Plus, Save, Search, Trash2, UserRound, X } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Client={id:string;nome:string;telefone?:string|null;email?:string|null;cidade?:string|null;objetivo?:string|null;faixa_investimento?:number|null;entrada_disponivel?:number|null;capacidade_mensal?:number|null;aceita_baloes?:boolean|null;balao_maximo?:number|null;cidades_preferencia?:string[]|null;status?:string|null;proximo_contato?:string|null;observacoes?:string|null};
type Property={id:string;nome?:string|null;cidade?:string|null;bairro?:string|null;status?:string|null;imagem_url?:string|null;descricao?:string|null;faixa_preco?:number|null;area_minima?:number|null;area_maxima?:number|null;caracteristicas?:Record<string,any>|null};
type Selection={cliente_id:string;empreendimento_id:string;ordem:number;motivo?:string|null};
type Form={nome:string;telefone:string;email:string;cidade:string;objetivo:string;faixa_investimento:string;entrada_disponivel:string;capacidade_mensal:string;aceita_baloes:boolean;balao_maximo:string;cidades_preferencia:string;status:string;proximo_contato:string;observacoes:string};
const empty:Form={nome:"",telefone:"",email:"",cidade:"",objetivo:"investimento",faixa_investimento:"",entrada_disponivel:"",capacidade_mensal:"",aceita_baloes:false,balao_maximo:"",cidades_preferencia:"",status:"novo",proximo_contato:"",observacoes:""};
const money=(value?:number|null)=>value?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",minimumFractionDigits:2,maximumFractionDigits:2}).format(value):"Não informado";
const panel={background:"#101012",border:"1px solid #27272a",borderRadius:11,padding:16} as const;
const input={width:"100%",boxSizing:"border-box",background:"#09090b",border:"1px solid #3f3f46",borderRadius:7,padding:10,color:"#fff"} as const;
const button={display:"inline-flex",alignItems:"center",justifyContent:"center",gap:6,background:"#c5a059",color:"#09090b",border:0,borderRadius:7,padding:"10px 13px",fontWeight:800,cursor:"pointer"} as const;
const normalizePhone=(value:string)=>{const digits=value.replace(/\D/g,"");return digits.length<=11?`55${digits}`:digits};

export default function Clientes(){
  const[items,setItems]=useState<Client[]>([]),[properties,setProperties]=useState<Property[]>([]),[selections,setSelections]=useState<Selection[]>([]);
  const[form,setForm]=useState<Form>(empty),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  const[editingId,setEditingId]=useState<string|null>(null),[curating,setCurating]=useState<Client|null>(null),[comparing,setComparing]=useState<Client|null>(null);

  async function load(){
    const[c,p,s]=await Promise.all([
      supabase.from("clientes").select("*").order("created_at",{ascending:false}),
      supabase.from("empreendimentos").select("id,nome,cidade,bairro,status,imagem_url,descricao,faixa_preco,area_minima,area_maxima,caracteristicas,ativo").eq("ativo",true).order("nome"),
      supabase.from("cliente_empreendimentos").select("*").order("ordem")
    ]);
    if(c.error)setMessage("Aplique a atualização de clientes no Supabase para ativar o módulo.");else setItems((c.data||[]) as Client[]);
    if(!p.error)setProperties((p.data||[]) as Property[]);
    if(!s.error)setSelections((s.data||[]) as Selection[]);
  }
  useEffect(()=>{void load()},[]);
  const visible=useMemo(()=>items.filter((item)=>`${item.nome} ${item.telefone} ${item.email} ${item.cidade}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const selectedFor=(clientId:string)=>selections.filter((item)=>item.cliente_id===clientId).sort((a,b)=>a.ordem-b.ordem);
  const propertiesFor=(clientId:string)=>selectedFor(clientId).map((selection)=>properties.find((item)=>item.id===selection.empreendimento_id)).filter(Boolean) as Property[];
  const update=(key:keyof Form,value:string|boolean)=>setForm((old)=>({...old,[key]:value}));
  const edit=(item:Client)=>{setEditingId(item.id);setForm({nome:item.nome,telefone:item.telefone||"",email:item.email||"",cidade:item.cidade||"",objetivo:item.objetivo||"investimento",faixa_investimento:String(item.faixa_investimento||""),entrada_disponivel:String(item.entrada_disponivel||""),capacidade_mensal:String(item.capacidade_mensal||""),aceita_baloes:Boolean(item.aceita_baloes),balao_maximo:String(item.balao_maximo||""),cidades_preferencia:(item.cidades_preferencia||[]).join(", "),status:item.status||"novo",proximo_contato:item.proximo_contato||"",observacoes:item.observacoes||""});setOpen(true)};
  const remove=async(item:Client)=>{if(!confirm(`Excluir o cliente ${item.nome}?`))return;const{error}=await supabase.from("clientes").delete().eq("id",item.id);setMessage(error?.message||"Cliente excluído.");if(!error)void load()};
  async function save(){if(!form.nome.trim())return setMessage("Informe o nome do cliente.");setSaving(true);const payload={nome:form.nome.trim(),telefone:form.telefone.trim()||null,email:form.email.trim()||null,cidade:form.cidade.trim()||null,objetivo:form.objetivo,faixa_investimento:Number(form.faixa_investimento)||null,entrada_disponivel:Number(form.entrada_disponivel)||null,capacidade_mensal:Number(form.capacidade_mensal)||null,aceita_baloes:form.aceita_baloes,balao_maximo:form.aceita_baloes?Number(form.balao_maximo)||null:null,cidades_preferencia:form.cidades_preferencia.split(",").map((item)=>item.trim()).filter(Boolean),status:form.status,proximo_contato:form.proximo_contato||null,observacoes:form.observacoes.trim()||null};const result=editingId?await supabase.from("clientes").update(payload).eq("id",editingId):await supabase.from("clientes").insert(payload);setSaving(false);if(result.error)setMessage("Não foi possível salvar. Confira se a atualização do banco foi aplicada.");else{setEditingId(null);setForm(empty);setOpen(false);void load()}}
  async function toggleProperty(client:Client,property:Property){
    const current=selectedFor(client.id),existing=current.find((item)=>item.empreendimento_id===property.id);
    if(existing){const{error}=await supabase.from("cliente_empreendimentos").delete().eq("cliente_id",client.id).eq("empreendimento_id",property.id);if(error)return setMessage(error.message)}
    else{if(current.length>=4)return setMessage("A comparação aceita no máximo quatro empreendimentos.");const used=new Set(current.map((item)=>item.ordem));const nextOrder=[1,2,3,4].find((value)=>!used.has(value))||4;const{error}=await supabase.from("cliente_empreendimentos").insert({cliente_id:client.id,empreendimento_id:property.id,ordem:nextOrder,motivo:"Selecionado para a curadoria do cliente"});if(error)return setMessage(error.message)}
    setMessage("");void load();
  }

  return <div style={{color:"#f4f4f5",display:"grid",gap:14}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,flexWrap:"wrap"}}><div><h1 style={{margin:0,fontSize:24}}>Clientes & Curadoria</h1><p style={{color:"#8b8b95",margin:"5px 0 0",fontSize:12}}>Perfil financeiro, preferências e até quatro empreendimentos comparáveis.</p></div><button style={button} onClick={()=>{setEditingId(null);setForm(empty);setOpen(true)}}><Plus size={16}/>Novo cliente</button></header>
    {message&&<div style={{...panel,borderColor:"#854d0e",color:"#fbbf24"}}>{message}</div>}
    <section style={panel}><div style={{display:"flex",alignItems:"center",gap:8}}><Search size={16} color="#71717a"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar por nome, telefone, e-mail ou cidade" style={input}/></div></section>
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:12}}>{visible.map((item)=>{const count=selectedFor(item.id).length;return <article key={item.id} style={panel}>
      <div style={{display:"flex",gap:10,alignItems:"center"}}><UserRound size={19} color="#c5a059"/><div style={{flex:1,minWidth:0}}><strong>{item.nome}</strong><small style={{display:"block",color:"#8b8b95",marginTop:3}}>{item.cidade||"Cidade não informada"}</small></div><button onClick={()=>edit(item)} title="Editar"><Pencil size={14}/></button><button onClick={()=>void remove(item)} title="Excluir"><Trash2 size={14}/></button></div>
      <div style={{display:"flex",gap:7,marginTop:11,flexWrap:"wrap"}}>{item.telefone&&<a href={`https://wa.me/${normalizePhone(item.telefone)}`} target="_blank" rel="noreferrer" style={{...button,padding:"7px 9px",fontSize:11,textDecoration:"none",background:"#14532d",color:"#dcfce7"}}><MessageCircle size={14}/>WhatsApp</a>}{item.email&&<a href={`mailto:${item.email}`} style={{color:"#c5a059",fontSize:11,alignSelf:"center"}}>{item.email}</a>}</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:14,fontSize:12}}><span style={{color:"#8b8b95"}}>Imóvel desejado<strong style={{display:"block",color:"#fff",marginTop:3}}>{money(item.faixa_investimento)}</strong></span><span style={{color:"#8b8b95"}}>Entrada<strong style={{display:"block",color:"#fff",marginTop:3}}>{money(item.entrada_disponivel)}</strong></span><span style={{color:"#8b8b95"}}>Parcela<strong style={{display:"block",color:"#fff",marginTop:3}}>{money(item.capacidade_mensal)}</strong></span><span style={{color:"#8b8b95"}}>Balão<strong style={{display:"block",color:"#fff",marginTop:3}}>{item.aceita_baloes?money(item.balao_maximo):"Não informado"}</strong></span></div>
      <div style={{marginTop:12,paddingTop:12,borderTop:"1px solid #27272a",display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>setCurating(item)} style={{...button,background:"#27272a",color:"#fff",fontSize:11}}><Plus size={14}/>Selecionar imóveis ({count}/4)</button>{count>0&&<button onClick={()=>setComparing(item)} style={{...button,fontSize:11}}><BarChart3 size={14}/>Comparar</button>}</div>
    </article>})}</section>

    {open&&<div style={{position:"fixed",inset:0,zIndex:5000,background:"rgba(0,0,0,.78)",display:"grid",placeItems:"center",padding:20}}><section style={{...panel,width:"min(800px,100%)",maxHeight:"88vh",overflow:"auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><h2 style={{margin:0,fontSize:18}}>{editingId?"Editar cliente":"Novo cliente"}</h2><button onClick={()=>setOpen(false)} style={{background:"none",border:0,color:"#aaa"}}><X/></button></header><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:11}}>
      {([["nome","Nome *","text"],["telefone","Telefone / WhatsApp","text"],["email","E-mail","email"],["cidade","Cidade onde mora","text"],["faixa_investimento","Valor do imóvel desejado","number"],["entrada_disponivel","Entrada disponível","number"],["capacidade_mensal","Parcela mensal confortável","number"],["balao_maximo","Balão máximo","number"],["proximo_contato","Próximo contato","date"]] as Array<[keyof Form,string,string]>).map(([key,label,type])=><label key={key} style={{color:"#a1a1aa",fontSize:12}}>{label}<input type={type} disabled={key==="balao_maximo"&&!form.aceita_baloes} value={String(form[key])} onChange={(e)=>update(key,e.target.value)} style={{...input,marginTop:5}}/></label>)}
      <label style={{color:"#a1a1aa",fontSize:12}}>Cidades de preferência (separe por vírgula)<input value={form.cidades_preferencia} onChange={(e)=>update("cidades_preferencia",e.target.value)} style={{...input,marginTop:5}}/></label>
      <label style={{color:"#a1a1aa",fontSize:12}}>Objetivo<select value={form.objetivo} onChange={(e)=>update("objetivo",e.target.value)} style={{...input,marginTop:5}}><option value="investimento">Investimento</option><option value="moradia">Moradia</option><option value="renda">Renda</option><option value="revenda">Revenda</option></select></label>
      <label style={{color:"#a1a1aa",fontSize:12}}>Etapa<select value={form.status} onChange={(e)=>update("status",e.target.value)} style={{...input,marginTop:5}}><option value="novo">Novo</option><option value="qualificado">Qualificado</option><option value="curadoria">Curadoria</option><option value="apresentacao">Apresentação</option><option value="proposta">Proposta</option><option value="negociacao">Negociação</option></select></label>
      <label style={{color:"#a1a1aa",fontSize:12,display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={form.aceita_baloes} onChange={(e)=>update("aceita_baloes",e.target.checked)}/>Cliente aceita balões</label>
      <label style={{color:"#a1a1aa",fontSize:12,gridColumn:"1/-1"}}>Observações<textarea value={form.observacoes} onChange={(e)=>update("observacoes",e.target.value)} rows={4} style={{...input,marginTop:5}}/></label>
    </div><div style={{display:"flex",justifyContent:"flex-end",marginTop:15}}><button style={button} onClick={()=>void save()} disabled={saving}><Save size={16}/>{saving?"Salvando...":"Salvar cliente"}</button></div></section></div>}

    {curating&&<div style={{position:"fixed",inset:0,zIndex:5000,background:"rgba(0,0,0,.82)",padding:24,overflow:"auto"}}><section style={{maxWidth:1180,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div><h2 style={{margin:0}}>Curadoria para {curating.nome}</h2><p style={{color:"#8b8b95"}}>Selecione de um a quatro empreendimentos. Pré-lançamentos permanecem em ambiente restrito.</p></div><button onClick={()=>setCurating(null)}><X/></button></header><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12}}>{properties.map((property)=>{const checked=selectedFor(curating.id).some((item)=>item.empreendimento_id===property.id);return <article key={property.id} style={{...panel,borderColor:checked?"#c5a059":"#27272a",padding:0,overflow:"hidden"}}>{property.imagem_url?<img src={property.imagem_url} alt="" style={{width:"100%",height:145,objectFit:"cover"}}/>:<div style={{height:145,background:"#18181b"}}/>}<div style={{padding:14}}><small style={{color:"#c5a059"}}>{property.status}</small><h3>{property.nome}</h3><p style={{color:"#8b8b95",fontSize:12}}>{property.cidade} · {money(property.faixa_preco)}</p><button onClick={()=>void toggleProperty(curating,property)} style={{...button,width:"100%",background:checked?"#14532d":"#c5a059",color:checked?"#dcfce7":"#09090b"}}>{checked?<Check size={15}/>:<Plus size={15}/>} {checked?"Selecionado":"Adicionar à comparação"}</button></div></article>})}</div></section></div>}

    {comparing&&<div style={{position:"fixed",inset:0,zIndex:5000,background:"#09090bf5",padding:24,overflow:"auto"}}><section style={{maxWidth:1280,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div><h2 style={{margin:0}}>Comparação para {comparing.nome}</h2><p style={{color:"#8b8b95"}}>{propertiesFor(comparing.id).length} empreendimento(s) selecionado(s)</p></div><button onClick={()=>setComparing(null)}><X/></button></header><div style={{display:"grid",gridTemplateColumns:`repeat(${Math.min(4,Math.max(1,propertiesFor(comparing.id).length))},minmax(220px,1fr))`,gap:12}}>{propertiesFor(comparing.id).map((property)=><article key={property.id} style={{...panel,padding:0,overflow:"hidden"}}>{property.imagem_url?<img src={property.imagem_url} alt="" style={{width:"100%",height:170,objectFit:"cover"}}/>:<div style={{height:170,background:"#18181b"}}/>}<div style={{padding:15}}><small style={{color:"#c5a059"}}>{property.status}</small><h3>{property.nome}</h3><p style={{color:"#a1a1aa",fontSize:12}}>{property.bairro} · {property.cidade}</p><dl style={{display:"grid",gap:8,fontSize:12}}><div><dt style={{color:"#71717a"}}>Valor inicial</dt><dd style={{margin:2,color:"#fff"}}>{money(property.faixa_preco)}</dd></div><div><dt style={{color:"#71717a"}}>Área</dt><dd style={{margin:2,color:"#fff"}}>{property.area_minima||"—"}–{property.area_maxima||"—"} m²</dd></div><div><dt style={{color:"#71717a"}}>Tipologias</dt><dd style={{margin:2,color:"#fff"}}>{Array.isArray(property.caracteristicas?.tipologias)?property.caracteristicas.tipologias.join(" · "):"Consulte"}</dd></div></dl></div></article>)}</div></section></div>}
  </div>;
}
