import { useMemo, useState } from "react";
import { Check, ChevronRight, RotateCcw, Sparkles } from "lucide-react";

type Mode = "entender" | "revisar" | "testar";
type Lesson = { id: string; title: string; summary: string; facts: string[]; connection: string; question: string };
type Topic = { id: string; title: string; subtitle: string; image: string; source: string; lessons: Lesson[] };

const topics: Topic[] = [
  { id: "carros", title: "Carros e motores", subtitle: "combustão, híbridos, elétricos e leitura de contexto", image: "/especialista/carros-eletrico.jpg", source: "NSC STEM Pathways / OLI — imagem de referência", lessons: [
    { id: "motor", title: "Como ler um motor", summary: "Cilindrada, torque, potência e tipo de alimentação explicam experiências diferentes — nenhum indicador isolado define preço ou patrimônio.", facts: ["Potência indica capacidade de realizar trabalho em determinada faixa de rotação.", "Torque ajuda a entender força de tração e resposta, especialmente em baixas rotações.", "Motores elétricos entregam torque imediato; motores a combustão trabalham com ciclos, rotação e transmissão."], connection: "Pergunta natural: você valoriza mais resposta, silêncio, economia, espaço ou prazer ao dirigir?", question: "Qual é a diferença prática entre torque e potência?" },
    { id: "eletrico", title: "Elétrico, híbrido e combustão", summary: "Tecnologias diferentes mudam manutenção, autonomia, recarga, uso urbano e viagem; a melhor escolha depende da rotina.", facts: ["Elétricos usam bateria, inversor e motor elétrico; a regeneração recupera parte da energia nas frenagens.", "Híbridos combinam motor a combustão e elétrico, com estratégias diferentes de recarga.", "Autonomia e infraestrutura são tão importantes quanto a potência declarada."], connection: "Conexão imobiliária: pergunte sobre garagem, carregamento, deslocamento e frequência de viagens.", question: "Que fatores devem ser comparados antes de falar que um carro elétrico é melhor?" },
    { id: "carroceria", title: "Carroceria e estilo de uso", summary: "Hatch, sedan, SUV, crossover, perua e picape comunicam necessidades de espaço e uso — não personalidade definitiva.", facts: ["Carroceria deve ser lida como hipótese de rotina: família, carga, estrada, cidade ou lazer.", "Marca, versão e estado de conservação importam mais que o formato isolado.", "Nunca deduza renda ou perfil financeiro apenas pelo carro."], connection: "Pergunta natural: o que nesse carro facilita a sua rotina?", question: "Por que carroceria não deve ser usada para presumir patrimônio?" },
  ] },
  { id: "cafes", title: "Cafés e gastronomia", subtitle: "origens, torra, preparo e conversa de hospitalidade", image: "/especialista/cafes-metodos.jpg", source: "Balance Coffee — imagem de referência", lessons: [
    { id: "preparo", title: "Métodos de preparo", summary: "Espresso, filtrado, prensa e moka produzem experiências diferentes por pressão, tempo, moagem e contato com a água.", facts: ["Espresso usa pressão e moagem fina para uma extração concentrada.", "Métodos filtrados destacam clareza e permitem perceber origem e torra.", "A moagem precisa conversar com o tempo de contato: mais fino extrai mais rapidamente; mais grosso, mais lentamente."], connection: "Pergunta natural: você gosta de um café mais intenso, doce, frutado ou ritualizado?", question: "O que muda entre espresso e filtrado além do tamanho da xícara?" },
    { id: "origem", title: "Origem, torra e sabor", summary: "Região, variedade, altitude, processamento e torra influenciam aroma e acidez; gosto é preferência, não hierarquia absoluta.", facts: ["Acidez pode ser uma qualidade sensorial, não significa necessariamente amargor.", "Torra mais escura tende a destacar notas tostadas e reduzir a percepção de origem.", "Notas sensoriais são descrições de percepção, não ingredientes adicionados."], connection: "Conexão regional: use cafés para falar de rotina, lugares favoritos e experiências no litoral.", question: "Como explicar acidez sem dizer que o café está azedo?" },
  ] },
  { id: "joias", title: "Joias e diamantes", subtitle: "materiais, cortes, relógios e linguagem de elegância", image: "/especialista/joias-diamantes.jpg", source: "GIA — referência visual sobre gemas", lessons: [
    { id: "4cs", title: "Os 4Cs do diamante", summary: "Cut, Color, Clarity e Carat são dimensões diferentes; peso em quilates não resume beleza, raridade ou valor.", facts: ["Cut trata das proporções, simetria e acabamento que influenciam brilho.", "Color e clarity usam escalas próprias e devem ser interpretadas com certificação.", "Carat é massa, não tamanho visual universal: corte e formato também alteram a percepção."], connection: "Pergunta natural: você valoriza mais design, história, discrição, raridade ou certificação?", question: "Por que quilate sozinho não determina o valor de um diamante?" },
    { id: "materiais", title: "Metais, gemas e relógios", summary: "O especialista reconhece vocabulário, mas não deve transformar um objeto em diagnóstico de renda ou caráter.", facts: ["O mesmo design pode existir em metais, ligas e níveis de acabamento diferentes.", "Relógios envolvem movimento, complicações, materiais, história e serviço pós-venda.", "Autenticidade e procedência são indispensáveis antes de qualquer afirmação de valor."], connection: "Conexão comercial: pergunte o que a pessoa aprecia no objeto, não quanto ele custou.", question: "Qual é a pergunta segura ao notar uma joia ou relógio?" },
  ] },
  { id: "geografia", title: "Geografia e viagens", subtitle: "cidades, deslocamento, clima e experiências", image: "/especialista/cafes-metodos.jpg", source: "Imagem temporária de estudo — substituir por acervo regional licenciado", lessons: [{ id: "mapa", title: "Ler origem e destino", summary: "A cidade do cliente ajuda a entender deslocamento, repertório e barreiras para uma visita, mas nunca determina intenção.", facts: ["Pergunte sobre frequência de viagens e familiaridade com a região.", "Compare tempo de deslocamento, aeroportos, acesso rodoviário e rotina familiar.", "Penha, Piçarras e Barra Velha devem ser apresentadas por experiências e logística reais."], connection: "Pergunta natural: quando você vem ao litoral, o que precisa estar fácil para a viagem valer a pena?", question: "Qual informação geográfica ajuda a converter uma conversa em visita?" }] },
];

export default function EspecialistaKnowledge() {
  const [topicId, setTopicId] = useState("carros");
  const [lessonId, setLessonId] = useState("motor");
  const [mode, setMode] = useState<Mode>("entender");
  const [readCount, setReadCount] = useState(0);
  const topic = topics.find((item) => item.id === topicId) || topics[0];
  const lesson = topic.lessons.find((item) => item.id === lessonId) || topic.lessons[0];
  const changeTopic = (id: string) => { const next = topics.find((item) => item.id === id) || topics[0]; setTopicId(id); setLessonId(next.lessons[0].id); setReadCount(0); setMode("entender"); };
  const prompt = useMemo(() => mode === "revisar" ? `Explique novamente com suas palavras: ${lesson.summary}` : mode === "testar" ? lesson.question : lesson.connection, [lesson, mode]);
  return <aside style={aside}><div style={eyebrow}><Sparkles size={14} /> ESPECIALISTA · ESTUDO DIÁRIO</div><h2 style={{ margin: "8px 0 5px", fontSize: 20 }}>Aprender para conversar melhor</h2><p style={muted}>Escolha um assunto, leia a ficha e repita em três modos. O objetivo é criar repertório real, não decorar frases.</p><div style={topicList}>{topics.map((item) => <button key={item.id} onClick={() => changeTopic(item.id)} style={topicButton(item.id === topic.id)}><img src={item.image} alt="" style={thumb} /><span><strong>{item.title}</strong><small>{item.subtitle}</small></span><ChevronRight size={15} /></button>)}</div><div style={hero}><img src={topic.image} alt={topic.title} style={heroImage} /><div style={heroOverlay}><b>{topic.title}</b><small>{topic.source}</small></div></div><div style={tabs}>{([['entender', 'Entender'], ['revisar', 'Revisar'], ['testar', 'Testar']] as const).map(([id, label]) => <button key={id} onClick={() => setMode(id)} style={tab(mode === id)}>{label}</button>)}</div><div style={lessonCard}><small style={eyebrow}>{mode === "entender" ? "LEIA COM CALMA" : mode === "revisar" ? "FALE SEM CONSULTAR" : "RESPONDA"}</small><h3 style={{ margin: "7px 0" }}>{lesson.title}</h3>{mode !== "testar" && <p style={text}>{mode === "entender" ? lesson.summary : prompt}</p>}{mode === "entender" && <ul style={list}>{lesson.facts.map((fact) => <li key={fact}>{fact}</li>)}</ul>}{mode === "testar" && <p style={{ ...text, color: "#edcf91" }}>{lesson.question}</p>}<div style={connection}><b>Aplicação na conversa</b><p style={{ margin: "4px 0 0", color: "#ddd" }}>{mode === "testar" ? "Depois de responder, compare com a ficha e formule uma pergunta natural para o cliente." : lesson.connection}</p></div><button onClick={() => setReadCount((count) => count + 1)} style={readButton}><Check size={14} /> Marcar leitura {readCount > 0 ? `· ${readCount}x` : ""}</button></div><div style={lessonPicker}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><b>Fichas deste tema</b><button onClick={() => setReadCount(0)} style={reset}><RotateCcw size={13} /> zerar contador</button></div>{topic.lessons.map((item) => <button key={item.id} onClick={() => { setLessonId(item.id); setReadCount(0); setMode("entender"); }} style={lessonButton(item.id === lesson.id)}>{item.title}</button>)}</div></aside>;
}

const aside = { minWidth: 0, background: "#0d0d0f", border: "1px solid #302a20", borderRadius: 12, padding: 14, color: "#f4f4f5", display: "grid", gap: 11, alignSelf: "start", position: "sticky" as const, top: 14 };
const muted = { color: "#9b9ba3", fontSize: 12, lineHeight: 1.45, margin: 0 };
const eyebrow = { color: "#d7ab63", fontSize: 10, fontWeight: 800, letterSpacing: 1.1, display: "flex", gap: 5, alignItems: "center" };
const topicList = { display: "grid", gap: 6 };
const topicButton = (active: boolean) => ({ display: "flex", alignItems: "center", gap: 8, textAlign: "left" as const, cursor: "pointer", padding: 7, borderRadius: 8, border: `1px solid ${active ? "#80652f" : "#28282e"}`, background: active ? "#20180d" : "#131316", color: "#eee" });
const thumb = { width: 38, height: 32, objectFit: "cover" as const, borderRadius: 5 };
const hero = { height: 132, overflow: "hidden", borderRadius: 9, position: "relative" as const, background: "#191919" };
const heroImage = { width: "100%", height: "100%", objectFit: "cover" as const, opacity: .8 };
const heroOverlay = { position: "absolute" as const, inset: "auto 0 0", padding: "28px 10px 9px", display: "grid", gap: 3, background: "linear-gradient(transparent,rgba(0,0,0,.85))" };
const tabs = { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 5 };
const tab = (active: boolean) => ({ cursor: "pointer", padding: "7px 5px", borderRadius: 6, border: `1px solid ${active ? "#c5a059" : "#35353d"}`, background: active ? "#c5a059" : "#17171a", color: active ? "#17120a" : "#ddd", fontWeight: 800, fontSize: 11 });
const lessonCard = { padding: 12, border: "1px solid #3f3424", borderRadius: 9, background: "#17130d" };
const text = { color: "#d1d1d4", fontSize: 12, lineHeight: 1.5, margin: "7px 0" };
const list = { color: "#cfcfd2", fontSize: 11, lineHeight: 1.5, paddingLeft: 18, margin: "8px 0" };
const connection = { borderLeft: "2px solid #c5a059", paddingLeft: 9, margin: "10px 0", fontSize: 11, color: "#edcf91" };
const readButton = { display: "inline-flex", alignItems: "center", gap: 5, cursor: "pointer", border: 0, borderRadius: 6, padding: "8px 10px", background: "#c5a059", color: "#17120a", fontWeight: 800, fontSize: 11 };
const lessonPicker = { display: "grid", gap: 5, borderTop: "1px solid #29292e", paddingTop: 10 };
const lessonButton = (active: boolean) => ({ textAlign: "left" as const, cursor: "pointer", border: `1px solid ${active ? "#6d562c" : "#29292e"}`, background: active ? "#211a0d" : "#141416", color: active ? "#edcf91" : "#aaa", borderRadius: 6, padding: "7px 8px", fontSize: 11 });
const reset = { cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 4, border: 0, background: "transparent", color: "#888", fontSize: 10 };
