import { useEffect, useState } from "react";
import { Camera, KeyRound, Mail, Save, UserRound } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Profile={usuario:string|null;nome_exibicao:string|null;avatar_path:string|null;perfil:string;ativo:boolean};
const field:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#101014",border:"1px solid #35353d",borderRadius:7,color:"#fff",padding:"11px"};
const card:React.CSSProperties={background:"#111114",border:"1px solid #29292e",borderRadius:11,padding:18,display:"grid",gap:13};
const action:React.CSSProperties={display:"inline-flex",justifyContent:"center",alignItems:"center",gap:7,border:0,borderRadius:7,background:"#d7ab63",color:"#111",padding:"11px",fontWeight:800,cursor:"pointer"};

export default function MinhaConta({compact=false}:{compact?:boolean}){
 const [profile,setProfile]=useState<Profile|null>(null),[email,setEmail]=useState(""),[newEmail,setNewEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[avatarUrl,setAvatarUrl]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;setEmail(user.email||"");setNewEmail(user.email||"");const {data}=await supabase.from("perfis_usuario").select("usuario,nome_exibicao,avatar_path,perfil,ativo").eq("user_id",user.id).single();if(data){const next=data as Profile;setProfile(next);if(next.avatar_path){const signed=await supabase.storage.from("avatares").createSignedUrl(next.avatar_path,3600);setAvatarUrl(signed.data?.signedUrl||"")}}};
 useEffect(()=>{void load()},[]);
 const saveProfile=async()=>{if(!profile)return;setSaving(true);setMessage("");const {error}=await supabase.rpc("atualizar_meu_perfil",{p_usuario:profile.usuario||"",p_nome_exibicao:profile.nome_exibicao||"",p_avatar_path:profile.avatar_path||""});setSaving(false);setMessage(error?error.message.includes("USUARIO_EM_USO")?"Esse nickname já está em uso.":"Revise o nickname: use 3 a 24 letras, números, ponto, traço ou sublinhado.":"Perfil atualizado.")};
 const uploadAvatar=async(file?:File)=>{if(!file)return;if(!file.type.startsWith("image/")||file.size>5*1024*1024)return setMessage("Use uma foto de até 5 MB.");const {data:{user}}=await supabase.auth.getUser();if(!user)return;const extension=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${user.id}/perfil.${extension}`;const sent=await supabase.storage.from("avatares").upload(path,file,{upsert:true});if(sent.error)return setMessage(sent.error.message);setProfile(current=>current?{...current,avatar_path:path}:current);const signed=await supabase.storage.from("avatares").createSignedUrl(path,3600);setAvatarUrl(signed.data?.signedUrl||"");setMessage("Foto enviada. Clique em Salvar perfil para confirmar.")};
 const changeEmail=async()=>{if(!newEmail.includes('@'))return setMessage("Informe um e-mail válido.");const {error}=await supabase.auth.updateUser({email:newEmail.trim().toLowerCase()});setMessage(error?error.message:newEmail.toLowerCase()===email.toLowerCase()?"Este já é o e-mail cadastrado.":"Confirme a alteração no e-mail enviado pela plataforma.")};
 const changePassword=async()=>{if(password.length<8)return setMessage("A nova senha deve ter pelo menos 8 caracteres.");if(password!==confirm)return setMessage("As duas senhas não coincidem.");const {error}=await supabase.auth.updateUser({password});if(!error){setPassword("");setConfirm("")}setMessage(error?error.message:"Senha alterada com sucesso.")};
 if(!profile)return <p style={{color:"#aaa"}}>Carregando sua conta…</p>;
 return <section style={{maxWidth:compact?900:1100,margin:"0 auto",display:"grid",gap:16}}>{!compact&&<header><small style={{color:"#d7ab63",fontWeight:800}}>PERFIL E SEGURANÇA</small><h1 style={{margin:"6px 0"}}>Minha conta</h1><p style={{margin:0,color:"#999"}}>Veja claramente como você entra no sistema e mantenha seus dados atualizados.</p></header>}{message&&<div style={{padding:11,border:"1px solid #6a5229",borderRadius:7,color:"#edcf91"}}>{message}</div>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14}}><article style={card}><h2 style={{fontSize:17,margin:0}}><UserRound size={18}/> Perfil</h2><div style={{display:"flex",alignItems:"center",gap:13}}>{avatarUrl?<img src={avatarUrl} alt="Foto do perfil" style={{width:72,height:72,borderRadius:"50%",objectFit:"cover"}}/>:<div style={{width:72,height:72,borderRadius:"50%",display:"grid",placeItems:"center",background:"#242018",color:"#d7ab63"}}><UserRound size={30}/></div>}<label style={{...action,background:"#242018",color:"#edcf91"}}><Camera size={16}/>Trocar foto<input hidden type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>void uploadAvatar(e.target.files?.[0])}/></label></div><label>Nome de exibição<input style={{...field,marginTop:6}} value={profile.nome_exibicao||""} onChange={e=>setProfile({...profile,nome_exibicao:e.target.value})}/></label><label>Nickname de acesso<input style={{...field,marginTop:6}} autoCapitalize="none" value={profile.usuario||""} onChange={e=>setProfile({...profile,usuario:e.target.value.toLowerCase()})} placeholder="ex.: luan.especialista"/></label><small style={{color:"#888"}}>Perfil: {profile.perfil} · {profile.ativo?"acesso ativo":"acesso bloqueado"}</small><button style={action} disabled={saving} onClick={()=>void saveProfile()}><Save size={16}/>{saving?"Salvando…":"Salvar perfil"}</button></article><article style={card}><h2 style={{fontSize:17,margin:0}}><Mail size={18}/> E-mail</h2><small style={{color:"#aaa"}}>E-mail atualmente cadastrado</small><strong>{email||"Não informado"}</strong><label>Novo e-mail<input type="email" style={{...field,marginTop:6}} value={newEmail} onChange={e=>setNewEmail(e.target.value)}/></label><button style={action} onClick={()=>void changeEmail()}>Solicitar alteração</button><small style={{color:"#888"}}>O e-mail continua sendo usado para confirmação e recuperação da conta.</small></article><article style={card}><h2 style={{fontSize:17,margin:0}}><KeyRound size={18}/> Senha</h2><input type="password" style={field} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nova senha — mínimo 8 caracteres"/><input type="password" style={field} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirmar nova senha"/><button style={action} onClick={()=>void changePassword()}>Alterar senha</button></article></div></section>;
}
