import { useMemo, useState } from "react";
import { CalendarCheck, Copy, Mail, MessageCircle, Phone, RotateCcw, Users } from "lucide-react";

type Channel = "ligacao" | "whatsapp" | "email" | "meet" | "visita";
type Tone = "consultiva" | "direta" | "premium";
type Line = { say: string; ask: string; cue: string };
type Lines = Record<Tone, Line>;

const tones: Tone[] = ["consultiva", "direta", "premium"];
const channels: Array<[Channel, string, typeof Phone]> = [["ligacao", "Ligação", Phone], ["whatsapp", "WhatsApp", MessageCircle], ["email", "E-mail", Mail], ["meet", "Meet", CalendarCheck], ["visita", "Visita", Users]];
const make = (consultiva: Line, direta: Line, premium: Line): Lines => ({ consultiva, direta, premium });
const base = (say: string, ask: string, cue: string): Line => ({ say, ask, cue });

const openings: Record<Channel, Lines> = {
  ligacao: make(base("Olá, [Nome], tudo bem? Aqui é [Seu nome], da Sol Imóveis. Posso tomar um minuto para entender seu momento e ver se existe algo que realmente valha sua atenção?", "Hoje você olha mais para morar, investir ou ter uma base no litoral?", "Faça a pergunta e espere. Não complete o silêncio."), base("Olá, [Nome]. Vou ser objetivo: vi seu interesse e quero evitar opções aleatórias. Posso fazer duas perguntas rápidas?", "Você busca moradia, investimento ou lazer — e qual faixa quer preservar?", "Objetividade sem pressa transmite segurança."), base("Olá, [Nome]. Antes de sugerir qualquer imóvel, quero entender qual decisão faria sentido para seu patrimônio e para sua rotina.", "Seu foco é preservar capital, gerar renda, ganhar localização ou reunir a família?", "Use tom calmo. Nunca invente exclusividade.")),
  whatsapp: make(base("Olá, [Nome]! Sou [Seu nome], da Sol Imóveis. Para não te enviar uma lista genérica: você está olhando algo para morar, investir ou aproveitar o litoral?", "Me responda com uma dessas opções e eu preparo um caminho objetivo.", "Uma pergunta por mensagem. Aguarde a resposta antes de anexar material."), base("Olá, [Nome]! Em vez de PDF demais, eu separo duas opções alinhadas ao seu objetivo.", "Você está em busca de moradia, investimento ou segunda residência?", "Mensagem curta, sem áudio longo e sem pressão."), base("Olá, [Nome]. Trabalho com uma curadoria pequena de oportunidades na região e posso te ajudar a filtrar o que faz sentido.", "Qual seria uma decisão bem-sucedida para você neste momento?", "Diagnóstico antes de catálogo.")),
  email: make(base("Assunto: uma seleção coerente para o seu momento\n\nOlá, [Nome]. Prefiro não enviar material genérico. Posso preparar uma leitura curta conforme seu objetivo.", "Sua prioridade é moradia, investimento ou uso no litoral?", "Use e-mail para contexto e retome pelo WhatsApp."), base("Assunto: duas opções, sem excesso de material\n\nOlá, [Nome]. Tenho como selecionar somente alternativas coerentes para sua faixa e objetivo.", "Qual prioridade devo considerar primeiro?", "Não coloque anexos antes de saber o objetivo."), base("Assunto: decisão imobiliária com mais clareza\n\nOlá, [Nome]. Uma boa decisão exige comparar fluxo, liquidez e uso — não apenas preço de tabela.", "Qual desses critérios merece maior peso para você hoje?", "Convide para uma conversa curta, não para apresentação longa.")),
  meet: make(base("Para não resolver uma decisão importante por mensagens soltas, posso mostrar duas opções e o fluxo em uma conversa de 15 minutos?", "Você prefere hoje no fim da tarde ou amanhã pela manhã?", "Ofereça duas janelas reais e confirme quem participa."), base("Isso fica mais claro em 15 minutos de tela compartilhada do que em vinte mensagens.", "Funciona melhor hoje às [hora A] ou amanhã às [hora B]?", "Duas opções de horário, nunca pergunta vaga."), base("Posso organizar uma leitura executiva: duas alternativas, pontos de atenção e fluxo comparado. Sem compromisso de decisão.", "Qual janela é mais confortável: [hora A] ou [hora B]?", "Envie pauta e duração ao confirmar.")),
  visita: make(base("Pelo que você valorizou, faz sentido ver isso ao vivo. Posso organizar uma visita objetiva, com duas opções comparáveis e sem compromisso de decisão?", "Você prefere [dia/horário A] ou [dia/horário B]?", "Confirme localização, objetivo e deslocamento antes de marcar."), base("Em vez de visitar dez lugares, eu separo dois que atendem ao que você disse.", "Fica melhor [dia/horário A] ou [dia/horário B]?", "Visita com critério, não passeio."), base("Posso preparar uma visita privada e enxuta: chegada, comparação e próximos passos — no seu ritmo.", "Qual data permite que todos os decisores estejam presentes?", "Convide parceiro(a) e decisores naturalmente.")),
};

const situations: Record<string, { title: string; lines: Lines; channel?: Channel }> = {
  preco: { title: "Só quero preço", lines: make(base("Claro, eu passo uma faixa agora. Só me ajuda a não te dar um número sem contexto: você compara valor total, entrada mensal ou custo até as chaves?", "Qual desses três precisa caber melhor?", "Depois entregue faixa e duas opções; não despeje tabela inteira."), base("Posso passar preço. Qual teto de investimento você considera e quanto quer comprometer até as chaves?", "Com isso eu elimino o que não cabe no seu cenário.", "Preço sem fluxo é informação incompleta."), base("O valor correto depende de como o capital fica distribuído, não só da etiqueta. Posso mostrar duas faixas com entrada, reforços e saldo?", "Seu parâmetro principal é liquidez, parcela ou patrimônio final?", "Apresente números auditáveis; nunca prometa retorno.")) },
  reuniao: { title: "Estou em reunião", channel: "whatsapp", lines: make(base("Perfeito, não vou te atrapalhar. Posso te deixar uma mensagem curta e você responde quando puder?", "Prefere que eu retome no fim do dia ou amanhã?", "Anote e cumpra o horário combinado."), base("Sem problema. Qual horário objetivo para eu retomar: [hora A] ou [hora B]?", "Posso te mandar uma linha de contexto no WhatsApp agora?", "Não tente continuar a ligação."), base("Compreendo. Para respeitar sua agenda, deixo um resumo e só retomo na janela que você indicar.", "Qual horário fica mais confortável?", "Silêncio não é permissão para insistência.")) },
  material: { title: "PDF, planilha e valores", channel: "whatsapp", lines: make(base("Claro, eu envio. Para não te afogar em PDF e tabela desatualizada: você prefere uma opção para morar e outra para investir, ou quer focar em uma delas?", "Me diga isso e envio só duas opções com valores e fluxo atuais.", "Envie no máximo duas opções e retorne com A ou B."), base("Eu mando. Só preciso definir o filtro: moradia, investimento ou segunda residência?", "E qual faixa de entrada é confortável?", "Material sem contexto diminui a curadoria."), base("Posso preparar um dossiê breve, com o que importa para sua decisão e sem material repetido.", "Você quer priorizar experiência de uso, renda potencial ou liquidez?", "Converta catálogo em recomendação.")) },
  caro: { title: "Está caro", lines: make(base("Entendo. Quando você diz caro, está comparando valor total, entrada, parcela, localização ou outra região?", "Qual parte do fluxo precisaria ficar confortável?", "Não rebata. Descubra o critério antes de defender valor."), base("Pode estar fora do que você quer comprometer. Qual número faria a conversa valer a pena?", "É entrada, parcela ou valor final?", "Se não há encaixe, ajuste a busca ou encerre com respeito."), base("Uma decisão premium não é pagar mais; é saber pelo que se paga e qual liquidez fica preservada.", "Quer que eu compare esta alternativa com uma opção que respeite seu limite?", "Fale de valor com evidência, não pressão.")) },
  pensar: { title: "Vou pensar", lines: make(base("Claro. O que ainda precisa ficar claro para você pensar com segurança?", "É fluxo, localização, construtora ou comparação com outra opção?", "Transforme ‘vou pensar’ em pendência objetiva."), base("Perfeito. Qual é a principal dúvida que precisa ser resolvida antes do próximo passo?", "Posso te devolver isso em [data]?", "Combine uma ação e data ou encerre sem insistência."), base("Decisões relevantes pedem tempo. Posso deixar uma comparação executiva para sua reflexão e retomar apenas quando fizer sentido?", "Qual informação aumentaria sua confiança?", "Respeito ao tempo é parte da experiência.")) },
  entrada: { title: "Não tenho entrada", lines: make(base("Obrigado por falar com clareza. Vamos entender qual entrada, parcela e reforço seriam saudáveis para você?", "Seu cenário pode melhorar em alguns meses ou existe um ativo para compor proposta?", "Nunca prometa aprovação; mostre fluxos condicionados à construtora."), base("Não vou te empurrar uma unidade. Qual valor você consegue aportar agora e por mês sem apertar sua vida?", "Há renda futura, FGTS, imóvel, veículo ou outro ativo a avaliar?", "Permuta é proposta sujeita a análise."), base("Capital inicial não é o único componente; importa proteger sua capacidade mensal e construir uma proposta viável.", "Quer que eu simule entrada menor, mais prazo ou ativo em permuta?", "Use cenários, não garantias.")) },
  cdi: { title: "Comparando com CDI", lines: make(base("É uma comparação inteligente. Vamos colocar liquidez, imposto, risco, aportes e cenário de saída lado a lado?", "Você pretende precisar desse dinheiro em quanto tempo?", "Não prometa rentabilidade; apresente premissas e cenários."), base("CDI é uma referência válida. Qual prazo e qual liquidez você precisa preservar?", "O objetivo é renda, proteção ou valorização?", "Mostre IR no resgate e custos; não compare números brutos."), base("Podemos comparar patrimônio líquido, não apenas percentual: caixa por data, tributos, liquidez e saída projetada.", "Posso montar cenários conservador, base e otimista?", "Explique premissas e limites da projeção.")) },
  parceiro: { title: "Falar com parceiro(a)", channel: "meet", lines: make(base("Faz sentido. Posso preparar um resumo curto para vocês verem juntos?", "Qual dúvida seu parceiro(a) faria primeiro: segurança, valor, localização ou fluxo?", "Convide o decisor sem pressionar."), base("Vamos evitar versões diferentes da mesma informação: posso marcar 15 minutos com vocês dois?", "Qual horário permite conversarmos juntos?", "Não induza urgência artificial."), base("Uma decisão compartilhada merece uma leitura comum. Posso levar duas opções com os trade-offs claros para vocês?", "O que mais pesa para a família nesta escolha?", "Ouça o decisor ausente antes de concluir.")) },
  corretor: { title: "Já tenho corretor", lines: make(base("Perfeito; o importante é você ser bem atendido. Posso deixar uma segunda leitura objetiva, sem compromisso?", "Há algo que ainda não ficou claro para você?", "Nunca ataque concorrente."), base("Ótimo. Não quero interferir. Se fizer sentido, fico como segunda opinião técnica para fluxo e comparação.", "Qual informação você sente falta hoje?", "Ofereça utilidade concreta, não disputa."), base("Ter um profissional de confiança é positivo. Minha contribuição pode ser uma análise independente de cenário e liquidez.", "Quer receber esse comparativo sem alterar seu atendimento atual?", "Respeite a autonomia do cliente.")) },
  investidor: { title: "Quero investir", lines: make(base("Ótimo. Para eu não chamar qualquer imóvel de investimento: qual papel ele deve cumprir — renda, valorização, proteção ou liquidez?", "Qual aporte e horizonte você considera?", "Não use cap rate ou TIR sem premissas completas."), base("Vamos começar pelo objetivo: renda agora, revenda, valorização ou diversificação?", "Qual prazo de saída você aceita?", "Separe imóvel de uso e tese de investimento."), base("Para patrimônio, eu comparo estratégia antes de produto: liquidez, risco, renda, saída e tributação.", "Sua prioridade é preservar caixa ou maximizar retorno potencial?", "Mostre cenários conservador, base e otimista.")) },
  silencio: { title: "Sem resposta", channel: "whatsapp", lines: make(base("Olá, [Nome]. Para respeitar seu tempo, vou encerrar por aqui por enquanto. Prefere uma comparação curta por WhatsApp ou que eu retome quando surgir algo alinhado?", "Responda só: comparação ou retomar depois.", "Cadência: ligação → WhatsApp → e-mail em 48h → 7 dias apenas com fato novo real."), base("Olá, [Nome]. Para eu organizar meu lado: você prefere uma seleção curta ou pausar por agora?", "Pode responder com ‘seleção’ ou ‘pausar’.", "Uma mensagem de encerramento é melhor que repetição."), base("Não quero transformar interesse em pressão. Posso permanecer disponível e retomar somente quando houver algo realmente aderente.", "Prefere que eu mantenha esse acompanhamento?", "Respeite ausência de resposta e preferências de contato.")) },
};

const responses = [["preco", "Só quero preço"], ["reuniao", "Estou em reunião"], ["material", "PDF, planilha e valores"], ["caro", "Está caro"], ["pensar", "Vou pensar"], ["entrada", "Não tenho entrada"], ["cdi", "Comparo com CDI"], ["parceiro", "Falar com parceiro(a)"], ["corretor", "Já tenho corretor"], ["investidor", "Quero investir"], ["silencio", "Sem resposta"]] as const;

export default function PlaybookModule() {
  const [channel, setChannel] = useState<Channel>("ligacao"); const [tone, setTone] = useState<Tone>("consultiva"); const [situation, setSituation] = useState<string | null>(null); const [history, setHistory] = useState<string[]>([]);
  const current = useMemo(() => (situation ? situations[situation].lines : openings[channel])[tone], [channel, situation, tone]);
  const choose = (id: string | null) => { if (id) { const item = situations[id]; if (item.channel) setChannel(item.channel); setHistory((items) => [...items, item.title]); } else setHistory([]); setSituation(id); };
  return <div style={{ color: "#eee", display: "grid", gap: 14, maxWidth: 1240 }}>
    <header><h1 style={{ margin: 0 }}>Playbook · conversa ao vivo</h1><p style={{ margin: "5px 0", color: "#aaa" }}>Escolha uma abordagem, leia a frase e toque na resposta real do cliente. Não é cadastro de lead.</p></header>
    <div style={grid}>{channels.map(([id, label, Icon]) => <button key={id} onClick={() => { setChannel(id); choose(null); }} style={chip(channel === id)}><Icon size={15} /> {label}</button>)}</div>
    <section style={{ border: "1px solid #795e2f", borderRadius: 10, padding: 16, background: "#15110b", display: "grid", gap: 13 }}>
      <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}><small style={{ color: "#d7ab63", fontWeight: 800 }}>FRASE PARA USAR AGORA</small><span style={{ color: "#777" }}>· escolha o tom</span><div style={{ marginLeft: "auto", display: "flex", gap: 6 }}>{tones.map((id) => <button key={id} onClick={() => setTone(id)} style={mini(tone === id)}>{id[0].toUpperCase() + id.slice(1)}</button>)}</div></div>
      <p style={{ fontSize: 18, lineHeight: 1.55, margin: 0, whiteSpace: "pre-line" }}>{current.say}</p><div style={{ borderLeft: "3px solid #c5a059", paddingLeft: 12 }}><b>Pergunta seguinte</b><p style={{ margin: "5px 0 0" }}>{current.ask}</p></div><small style={{ color: "#aaa" }}><b>Como conduzir:</b> {current.cue}</small>
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button onClick={() => navigator.clipboard?.writeText(`${current.say}\n\n${current.ask}`)} style={gold}><Copy size={14} /> Copiar fala</button><button onClick={() => choose(null)} style={dark}><RotateCcw size={14} /> Recomeçar</button></div>
    </section>
    <section><b>O que o cliente acabou de dizer?</b><div style={{ display: "flex", gap: 7, flexWrap: "wrap", marginTop: 8 }}>{responses.map(([id, label]) => <button key={id} onClick={() => choose(id)} style={dark}>{label}</button>)}<button onClick={() => { setChannel("meet"); choose(null); }} style={dark}>Converter para Meet</button><button onClick={() => { setChannel("visita"); choose(null); }} style={dark}>Converter para visita</button></div></section>
    {history.length > 0 && <small style={{ color: "#888" }}>Caminho da conversa: {history.join(" → ")}</small>}<footer style={{ padding: 12, border: "1px solid #29292e", borderRadius: 8, color: "#aaa" }}>Princípio comercial: escuta, perguntas claras, dados reais e liberdade de escolha. Nada de falsa urgência, promessa de rentabilidade ou pressão.</footer>
  </div>;
}

const grid = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(145px, 1fr))", gap: 8 };
const chip = (active: boolean) => ({ padding: "10px 12px", cursor: "pointer", background: active ? "#271d0d" : "#121214", color: "#eee", border: `1px solid ${active ? "#c5a059" : "#34343a"}`, borderRadius: 7, display: "inline-flex", justifyContent: "center", alignItems: "center", gap: 6 });
const mini = (active: boolean) => ({ padding: "6px 9px", cursor: "pointer", background: active ? "#c5a059" : "#17171a", color: active ? "#17120a" : "#eee", border: "1px solid #4a4030", borderRadius: 6, fontWeight: 700 });
const dark = { background: "#101012", border: "1px solid #35353d", color: "#eee", padding: "9px 11px", borderRadius: 6, cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 6 };
const gold = { ...dark, background: "#c5a059", border: "1px solid #c5a059", color: "#17120a", fontWeight: 800 };
