import {useEffect,useState} from "react";
import {CheckCircle2,Copy,KeyRound,Plus,RefreshCw,UserCog,XCircle} from "lucide-react";
import {supabase} from "@/lib/supabase";

type Request={id:string;nome:string;email:string;tipo:"cliente"|"afiliado";status:string;solicitado_em:string};
const box={background:"#101012",border:"1px solid #29292e",borderRadius:12,padding:16} as const;
const input={background:"#09090b",border:"1px solid #3f3f46",borderRadius:8,padding:10,color:"#fff",width:"100%",boxSizing:"border-box"} as const;
const button={display:"inline-flex",alignItems:"center",justifyContent:"center",gap:7,border:0,borderRadius:8,padding:"9px 12px",fontWeight:800,cursor:"pointer",background:"#c5a059",color:"#09090b"} as const;

export default function UsuariosAcessos(){
 const[items,setItems]=useState<Request[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[credentials,setCredentials]=useState<{email:string;usuario:string;senha:string}|null>(null);
 const[manual,setManual]=useState(false),[form,setForm]=useState({nome:"",email:"",tipo:"cliente" as "cliente"|"afiliado"});
 async function load(){const{data,error}=await supabase.from("solicitacoes_acesso").select("*").order("solicitado_em",{ascending:false});setItems((data||[]) as Request[]);if(error)setMessage(error.message)}
 useEffect(()=>{void load()},[]);
 async function approve(item:Pick<Request,"id"|"nome"|"email"|"tipo">){setBusy(item.id);setMessage("");setCredentials(null);const{data:{session}}=await supabase.auth.getSession();if(!session){setBusy("");return setMessage("Sua sessão expirou. Saia do painel e entre novamente.")}const{data,error}=await supabase.functions.invoke("gerenciar-acesso",{headers:{Authorization:`Bearer ${session.access_token}`},body:{solicitacao_id:item.id.startsWith("manual-")?null:item.id,nome:item.nome,email:item.email,tipo:item.tipo}});setBusy("");if(error||data?.error){let detail=data?.error||error?.message;const response=(error as any)?.context;if(response?.json)try{detail=(await response.json())?.error||detail}catch{}return setMessage(detail||"Não foi possível aprovar.")}setCredentials({email:data.email,usuario:data.usuario,senha:data.temporary_password});setMessage("Acesso aprovado. Copie os dados agora: a senha inicial não ficará guardada nesta tela.");void load()}
 async function reject(item:Request){setBusy(item.id);const{error}=await supabase.from("solicitacoes_acesso").update({status:"recusada",analisado_em:new Date().toISOString()}).eq("id",item.id);setBusy("");setMessage(error?.message||"Solicitação recusada.");void load()}
 async function copy(){if(!credentials)return;await navigator.clipboard.writeText(`Acesso à plataforma Luan Especialista\nE-mail: ${credentials.email}\nUsuário: ${credentials.usuario}\nSenha inicial: ${credentials.senha}\nPainel: ${window.location.origin}/painel/\n\nVocê pode manter esta senha ou alterá-la em Minha conta.`);setMessage("Dados de acesso copiados. A nova senha que o cliente definir nunca ficará visível para o administrador.")}
 const manualItem={id:`manual-${Date.now()}`,...form,status:"pendente",solicitado_em:new Date().toISOString()};
 return <div style={{color:"#fff",display:"grid",gap:16}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><h1 style={{margin:0,display:"flex",gap:9,alignItems:"center"}}><UserCog color="#c5a059"/>Usuários e acessos</h1><p style={{color:"#8b8b95"}}>Aprove clientes e afiliados e gere o primeiro acesso sem compartilhar senhas.</p></div><div style={{display:"flex",gap:8}}><button style={{...button,background:"#27272a",color:"#fff"}} onClick={()=>void load()}><RefreshCw size={15}/>Atualizar</button><button style={button} onClick={()=>setManual(v=>!v)}><Plus size={15}/>Criar acesso</button></div></header>
  {message&&<div style={{...box,color:credentials?"#86efac":"#fbbf24"}}>{message}{credentials&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr)) auto",gap:8,marginTop:12,alignItems:"end"}}><label style={{fontSize:11,color:"#aaa"}}>E-mail<input readOnly value={credentials.email} style={{...input,marginTop:5}}/></label><label style={{fontSize:11,color:"#aaa"}}>Nickname<input readOnly value={credentials.usuario} style={{...input,marginTop:5}}/></label><label style={{fontSize:11,color:"#aaa"}}>Senha inicial<input readOnly value={credentials.senha} style={{...input,marginTop:5,fontFamily:"monospace",fontSize:16}}/></label><button style={button} onClick={()=>void copy()}><Copy size={15}/>Copiar dados</button></div>}</div>}
  {manual&&<section style={{...box,display:"grid",gap:10}}><h3 style={{margin:0}}>Cliente ou afiliado que pediu pelo WhatsApp</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:9}}><input style={input} placeholder="Nome" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><input style={input} type="email" placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><select style={input} value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value as any})}><option value="cliente">Cliente</option><option value="afiliado">Afiliado</option></select></div><button disabled={!form.nome||!form.email||Boolean(busy)} style={button} onClick={()=>void approve(manualItem)}><KeyRound size={15}/>Criar/vincular e gerar link seguro</button></section>}
  <section style={{display:"grid",gap:10}}>{items.map(item=><article key={item.id} style={{...box,display:"flex",alignItems:"center",gap:12,flexWrap:"wrap",opacity:item.status==="pendente"?1:.65}}><div style={{flex:1,minWidth:210}}><strong>{item.nome}</strong><small style={{display:"block",color:"#a1a1aa"}}>{item.email} · {item.tipo} · {new Date(item.solicitado_em).toLocaleString("pt-BR")}</small></div><span style={{color:item.status==="aprovada"?"#86efac":item.status==="recusada"?"#fca5a5":"#fbbf24"}}>{item.status}</span>{item.status==="pendente"&&<><button disabled={busy===item.id} style={button} onClick={()=>void approve(item)}><CheckCircle2 size={15}/>Aprovar</button><button disabled={busy===item.id} style={{...button,background:"#3f1d22",color:"#fecaca"}} onClick={()=>void reject(item)}><XCircle size={15}/>Recusar</button></>}</article>)}{!items.length&&<div style={box}>Nenhuma solicitação registrada. Para os pedidos antigos do WhatsApp, use “Criar acesso”.</div>}</section>
 </div>
}
